#!/bin/bash
# Generated by Chef

SMTP_FROM='<%= node.jenkins_integration.smtp.from %>'
SMTP_SERVER='<%= node.jenkins_integration.smtp.server %>:<%= node.jenkins_integration.smtp.port %>'
SMTP_USERNAME='<%= node.jenkins_integration.smtp.username %>'
SMTP_PASSWORD='<%= node.jenkins_integration.smtp.password %>'

# echo From: $SMTP_FROM
# echo To: $1
# echo Subject: $2
# echo Auth: $SMTP_USERNAME identified by $SMTP_PASSWORD at $SMTP_SERVER
# echo $3

/usr/bin/sendEmail -f "$SMTP_FROM" -t "$1" -u "$2" -s "$SMTP_SERVER" -xu "$SMTP_USERNAME" -xp "$SMTP_PASSWORD" -o "tls=yes" -m "$3"
