Vagrant::Config.run do |config|
  # box to build off of.
  config.vm.box = "natty-base"

  # cloud we're targeting
  cluster     = 'cocina'
  facet       = 'chef_server'
  facet_index = '0'
  node_name   = "#{cluster}-#{facet}-#{facet_index}"

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  # Host only network IP lets you access it via the IP.
  config.vm.network "33.33.33.20"

  # Mount this to see all our chefs and stuff
  config.vm.share_folder "cloud-base", "/cloud", "/cloud"

  config.vm.customize do |vm|
    # Name the VM
    vm.name        = node_name
    # Bump up the memory
    vm.memory_size = 640
    # Use the host resolver for DNS so that VPN continues to work within the VM
    vm.network_adapters.each do |na|
      if na.enabled? && na.nat_driver
        na.nat_driver.dns_use_host_resolver = true
      end
    end
  end

  # Enable provisioning with chef solo, specifying a cookbooks path (relative
  # to this Vagrantfile), and adding some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "/cloud/cookbooks"
    chef.roles_path     = "/cloud/roles"
    #
    chef.add_role       :base_role
    chef.add_role       :chef_client
    chef.add_role       :ssh
    # chef.add_role     :nfs_client
    #
    chef.add_recipe     'cloud_utils::virtualbox_metadata'
    #
    chef.json = {
      "node_name"       => node_name,
      "cluster_name"    => cluster,
      "facet_name"      => facet,
      "facet_index"     => facet_index,

      "chef_server" => {
        "server_url"    => "http://localhost:4000",
        "init_style"    => "runit",
        "webui_enabled" => true
      },
      "validation_client_name" => "chef-validator",
      "validation_client_file" => "/etc/chef/validation.pem",
      #
      "nfs" => { "mounts" => [
          ["/home/#{ENV['HOME']}", { "owner" => ENV['HOME'], "remote_path" => "/Users/#{ENV['HOME']}" } ],
        ] },
      "pkg_sets" => {
        "install"       => [ "base", "dev", "sysadmin", "text", "vagrant" ] },
      "server_tuning"   => { "swappiness" => "60", "overcommit_memory" => "1", "overcommit_ratio" => "100" },
      "java"            => { "install_flavor" =>"sun" },
      "apt"             => { "cloudera" => { "force_distro" => "maverick" } },
      "volumes" => {
          "root"        => { "scratch" => true, "device" => "/dev/mapper/natty--base-root","mount_point" => "/", "mountable" => false }
      }
    }
  end

end
